name: Pull request

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"
      - "awesome/**"
      - "scheme/**"
      - "scripts/render.py"
      - "scripts/check.py"
    types: [opened, synchronize]

jobs:
  test-data:
    name: Test Data
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
          cache: "pip"

      - name: Code tests
        timeout-minutes: 10
        uses: pre-commit/action@v3.0.1

      - name: Test awesome data
        run: |
          pip install -r requirements.txt
          make test
